version: '3.9'

services:
  vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    env_file:
      .env
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
